// Package generator executes code-generation templates against a parsed model
// to produce typed client libraries. It embeds all templates from the templates/
// directory and writes generated Go source files to the specified output directory.
package generator

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"unicode"

	"github.com/mlwelles/modusgraph-gen/cmd/modusgraph-gen/internal/model"
)

//go:embed templates/*.tmpl
var templateFS embed.FS

// header is prepended to every generated file.
const header = "// Code generated by modusGraphGen. DO NOT EDIT.\n\n"

// Config drives a generator run with separate output directories for
// schema-side and entity-side artifacts. All paths must be absolute.
type Config struct {
	// Output directories — all required (resolved by the caller's flag-parsing layer).
	SchemaDir       string // schema source dir AND default for schema-side marker output
	SchemaClientDir string // output dir for the schema-side aggregate Client (client_gen.go)
	EntityDir       string // entity (wrapper) types + accessors + options output
	EntityClientDir string // entity-side (wrapper) client + query trio output
	CLIDir          string // CLI main.go output

	// Package name overrides — empty means derived from the dir basename.
	EntityPackageName       string // package decl for files in EntityDir
	EntityClientPackageName string // package decl for files in EntityClientDir (often same as EntityPackageName)
	SchemaClientPackageName string // package decl for files in SchemaClientDir (often same as SchemaDir's pkg name)

	// Schema package metadata (resolved by parser).
	SchemaAlias      string // import alias for the schema package (e.g., "schema")
	SchemaImportPath string // full Go import path for the schema package

	// Toggles.
	NoSchemaClients bool // skip the schema-level aggregate Client emit
	NoEntities      bool // skip entity + accessors + options + wrapper_client + wrapper_entity_client + wrapper_query emits
	NoEntityClients bool // skip wrapper_client + wrapper_entity_client + wrapper_query emits only
	NoCLI           bool // skip cli emit

	// CLI tweaks.
	CLIName       string // name for the kong CLI binary (defaults to EntityPackageName)
	WithValidator bool   // wire in modusgraph.WithValidator in the generated CLI
	CLINoMain     bool   // emit the CLI as an importable library package (no func main); zero value keeps the standalone-binary default
	CLIPackage    string // package name for the CLI library when CLINoMain (default: <cli-name>cli)
}

// Generate renders all code-generation templates against pkg and writes the
// resulting Go source files into the directories specified by cfg.
func Generate(pkg *model.Package, cfg Config) error {
	// Default CLIName to the schema package name if not explicitly set.
	if pkg.CLIName == "" {
		if cfg.CLIName != "" {
			pkg.CLIName = cfg.CLIName
		} else {
			pkg.CLIName = pkg.Name
		}
	}

	// Apply WithValidator from cfg.
	pkg.WithValidator = cfg.WithValidator

	// Resolve CLI emit mode. CLINoMain (zero value false) keeps the historical
	// standalone-binary behavior; setting it emits an importable library package.
	pkg.CLIEmitMain = !cfg.CLINoMain
	if pkg.CLIEmitMain {
		pkg.CLIPackage = "main"
	} else if cfg.CLIPackage != "" {
		pkg.CLIPackage = cfg.CLIPackage
	} else {
		pkg.CLIPackage = sanitizePackageName(pkg.CLIName) + "cli"
	}

	// Sort entities by name for deterministic output.
	sort.Slice(pkg.Entities, func(i, j int) bool {
		return pkg.Entities[i].Name < pkg.Entities[j].Name
	})
	funcMap := template.FuncMap{
		"toLower":      strings.ToLower,
		"toUpper":      strings.ToUpper,
		"toSnakeCase":  toSnakeCase,
		"toCamelCase":  toCamelCase,
		"accessorName": accessorName,
		"toLowerCamel": toLowerCamel,
		"title":        strings.Title, //nolint:staticcheck
		"hasPrefix":    strings.HasPrefix,
		"hasSuffix":    strings.HasSuffix,
		"contains":     strings.Contains,
		"trimPrefix":   strings.TrimPrefix,
		"join":         strings.Join,
		"sub":          func(a, b int) int { return a - b },
		"add":          func(a, b int) int { return a + b },

		// Field helpers for templates.
		"scalarFields":                 scalarFields,
		"edgeFields":                   edgeFields,
		"filterableScalarFields":       filterableScalarFields,
		"filterTermType":               filterTermType,
		"filterGroupMethod":            filterGroupMethod,
		"searchPredicate":              searchPredicate,
		"externalImports":              externalImports,
		"nonSliceScalarFields":         nonSliceScalarFields,
		"privateFields":                privateFields,
		"privateScalarFields":          privateScalarFields,
		"privateSingularEdgeFields":    privateSingularEdgeFields,
		"privateMultiEdgeFields":       privateMultiEdgeFields,
		"privateSliceFields":           privateSliceFields,
		"allSingularEdgeFields":        allSingularEdgeFields,
		"allPointerSingularEdgeFields": allPointerSingularEdgeFields,
		"allValueSingularEdgeFields":   allValueSingularEdgeFields,
		"allSingularViaListFields":     allSingularViaListFields,
		"allMultiEdgeFields":           allMultiEdgeFields,
		"allSliceFields":               allSliceFields,
		"trimPointerPrefix":            trimPointerPrefix,
		"trimSlicePrefix":              trimSlicePrefix,
		"trimSliceOfPointerPrefix":     trimSliceOfPointerPrefix,
		"trimSchemaAlias":              trimSchemaAlias,
		"marshalFields":                marshalFields,
		"packageExternalImports":       packageExternalImports,
		"elemType":                     elemType,
		"cliType":                      cliType,
		"cliConvert":                   cliConvert,
		"cliSettable":                  cliSettable,
		"hasValidateTags":              hasValidateTags,
		"fieldsWithValidation":         fieldsWithValidation,
		"lcFirst":                      lcFirst,
		"concat": func(a, b []model.Field) []model.Field {
			return append(append([]model.Field{}, a...), b...)
		},
	}

	tmpl, err := template.New("").Funcs(funcMap).ParseFS(templateFS, "templates/*.tmpl")
	if err != nil {
		return fmt.Errorf("parsing templates: %w", err)
	}

	// Resolve package names, falling back to pkg.Name when overrides are empty.
	schemaClientPkg := cfg.SchemaClientPackageName
	if schemaClientPkg == "" {
		schemaClientPkg = pkg.Name
	}
	entityPkg := cfg.EntityPackageName
	if entityPkg == "" {
		entityPkg = "entity"
	}
	entityClientPkg := cfg.EntityClientPackageName
	if entityClientPkg == "" {
		entityClientPkg = entityPkg
	}
	schemaAlias := cfg.SchemaAlias
	if schemaAlias == "" {
		schemaAlias = pkg.Name
	}
	schemaImportPath := cfg.SchemaImportPath
	if schemaImportPath == "" {
		schemaImportPath = pkg.SchemaImportPath
	}

	// Validate that output directories for non-gated outputs are set, so a
	// missing dir never silently writes generated files into the current
	// working directory.
	if cfg.SchemaDir == "" {
		return fmt.Errorf("SchemaDir is required")
	}
	if !cfg.NoSchemaClients && cfg.SchemaClientDir == "" {
		return fmt.Errorf("SchemaClientDir is required when schema clients are enabled")
	}
	if !cfg.NoEntities {
		if cfg.EntityDir == "" {
			return fmt.Errorf("EntityDir is required when entities are enabled")
		}
		if !cfg.NoEntityClients && cfg.EntityClientDir == "" {
			return fmt.Errorf("EntityClientDir is required when entity clients are enabled")
		}
	}

	// Ensure output directories exist.
	for _, dir := range []string{cfg.SchemaDir, cfg.SchemaClientDir, cfg.EntityDir, cfg.EntityClientDir} {
		if dir == "" {
			continue
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("creating output directory %s: %w", dir, err)
		}
	}

	// 1. schema_marker.go.tmpl → marker_gen.go (SchemaDir, never gated)
	if err := executeAndWrite(tmpl, "schema_marker.go.tmpl", pkg, filepath.Join(cfg.SchemaDir, "marker_gen.go")); err != nil {
		return err
	}

	// 2. schema_client.go.tmpl → client_gen.go (SchemaClientDir, gated by NoSchemaClients)
	if !cfg.NoSchemaClients {
		schemaClientData := struct {
			Name     string
			Entities []model.Entity
		}{
			Name:     schemaClientPkg,
			Entities: pkg.Entities,
		}
		if err := executeAndWrite(tmpl, "schema_client.go.tmpl", schemaClientData, filepath.Join(cfg.SchemaClientDir, "client_gen.go")); err != nil {
			return err
		}
	}

	// 3. wrapper_client.go.tmpl → client_gen.go (EntityClientDir, gated by NoEntities || NoEntityClients)
	if !cfg.NoEntities && !cfg.NoEntityClients {
		wrapperClientData := struct {
			EntityPackageName string
			SchemaAlias       string
			SchemaImportPath  string
			Entities          []model.Entity
		}{
			EntityPackageName: entityClientPkg,
			SchemaAlias:       schemaAlias,
			SchemaImportPath:  schemaImportPath,
			Entities:          pkg.Entities,
		}
		if err := executeAndWrite(tmpl, "wrapper_client.go.tmpl", wrapperClientData, filepath.Join(cfg.EntityClientDir, "client_gen.go")); err != nil {
			return err
		}
	}

	// Per-entity data struct used by entity, options, accessors, and wrapper-side templates.
	type entityData struct {
		PackageName       string
		Entity            model.Entity
		Entities          []model.Entity
		Imports           map[string]string
		EntityPackageName string
		SchemaAlias       string
		SchemaImportPath  string
	}

	// Per-entity loop: render the five fragment templates and merge them into
	// one <entity>_gen.go per (directory, entity) group. In the default layout
	// EntityDir == EntityClientDir, so all five fragments land in one file;
	// when they differ, the entity-side fragments and client-side fragments
	// form two separate <entity>_gen.go files.
	for _, entity := range pkg.Entities {
		if cfg.NoEntities {
			break
		}
		snake := toSnakeCase(entity.Name)

		data := entityData{
			PackageName:       pkg.Name,
			Entity:            entity,
			Entities:          pkg.Entities,
			Imports:           pkg.Imports,
			EntityPackageName: entityPkg,
			SchemaAlias:       schemaAlias,
			SchemaImportPath:  schemaImportPath,
		}
		entityBody, err := render(tmpl, "entity.go.tmpl", data)
		if err != nil {
			return err
		}
		accessorsBody, err := render(tmpl, "accessors.go.tmpl", data)
		if err != nil {
			return err
		}
		optionsBody, err := render(tmpl, "options.go.tmpl", data)
		if err != nil {
			return err
		}

		// When wrapper clients are skipped, the merged file holds only the
		// three entity-side fragments.
		if cfg.NoEntityClients {
			imps := newGenImports()
			imps.addEntitySideImports(entity, pkg.Imports, schemaImportPath)
			content := assembleGenFile(entityPkg, imps.block(), entityBody, accessorsBody, optionsBody)
			if err := writeGoFile(filepath.Join(cfg.EntityDir, snake+"_gen.go"), content); err != nil {
				return err
			}
			continue
		}

		wrapData := data
		wrapData.EntityPackageName = entityClientPkg
		clientBody, err := render(tmpl, "wrapper_entity_client.go.tmpl", wrapData)
		if err != nil {
			return err
		}
		queryBody, err := render(tmpl, "wrapper_query.go.tmpl", wrapData)
		if err != nil {
			return err
		}

		if filepath.Clean(cfg.EntityDir) == filepath.Clean(cfg.EntityClientDir) {
			// Default layout: all five fragments in one file.
			imps := newGenImports()
			imps.addEntitySideImports(entity, pkg.Imports, schemaImportPath)
			imps.addClientSideImports(schemaImportPath, entity)
			content := assembleGenFile(entityPkg, imps.block(),
				entityBody, accessorsBody, optionsBody, clientBody, queryBody)
			if err := writeGoFile(filepath.Join(cfg.EntityDir, snake+"_gen.go"), content); err != nil {
				return err
			}
			continue
		}

		// Split layout: entity-side file in EntityDir, client-side file in
		// EntityClientDir, each named <entity>_gen.go.
		entityImps := newGenImports()
		entityImps.addEntitySideImports(entity, pkg.Imports, schemaImportPath)
		entityContent := assembleGenFile(entityPkg, entityImps.block(),
			entityBody, accessorsBody, optionsBody)
		if err := writeGoFile(filepath.Join(cfg.EntityDir, snake+"_gen.go"), entityContent); err != nil {
			return err
		}

		clientImps := newGenImports()
		clientImps.addClientSideImports(schemaImportPath, entity)
		clientContent := assembleGenFile(entityClientPkg, clientImps.block(), clientBody, queryBody)
		if err := writeGoFile(filepath.Join(cfg.EntityClientDir, snake+"_gen.go"), clientContent); err != nil {
			return err
		}
	}

	// cli.go.tmpl → main.go (standalone) or cli.go (library), gated by NoCLI.
	if !cfg.NoCLI && cfg.CLIDir != "" {
		if err := os.MkdirAll(cfg.CLIDir, 0o755); err != nil {
			return fmt.Errorf("creating CLI directory: %w", err)
		}
		cliFile := "main.go"
		if !pkg.CLIEmitMain {
			cliFile = "cli.go"
		}
		if err := executeAndWrite(tmpl, "cli.go.tmpl", pkg, filepath.Join(cfg.CLIDir, cliFile)); err != nil {
			return err
		}
	}

	return nil
}

// render executes a named template against data and returns the rendered body
// with no header. It is the building block for both standalone-file templates
// and merged per-entity files.
func render(tmpl *template.Template, name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("executing template %s: %w", name, err)
	}
	return buf.String(), nil
}

// writeGoFile prepends the generated-code header, gofmt-formats the result, and
// writes it to path. On a formatting error the raw output is written to
// path+".broken" for debugging.
func writeGoFile(path, content string) error {
	src := header + content
	formatted, err := format.Source([]byte(src))
	if err != nil {
		_ = os.WriteFile(path+".broken", []byte(src), 0o644)
		return fmt.Errorf("formatting %s: %w\nRaw output written to %s.broken", filepath.Base(path), err, path)
	}
	return os.WriteFile(path, formatted, 0o644)
}

// executeAndWrite renders a standalone-file template and writes the formatted
// result to path. Used by templates that emit a complete file with their own
// package/import header (wrapper_client, schema_client, schema_marker, cli).
func executeAndWrite(tmpl *template.Template, name string, data any, path string) error {
	body, err := render(tmpl, name, data)
	if err != nil {
		return err
	}
	return writeGoFile(path, body)
}

// toSnakeCase converts a Go identifier like "ContentRating" to "content_rating".
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := rune(s[i-1])
				if unicode.IsLower(prev) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1]))) {
					result.WriteRune('_')
				}
			}
			result.WriteRune(unicode.ToLower(r))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

// commonInitialisms is the canonical set of Go initialisms from golang.org/x/lint.
// These are uppercased as a whole word in CamelCase identifiers per Go conventions.
// Source: https://github.com/golang/lint/blob/master/lint.go (BSD-3-Clause)
var commonInitialisms = map[string]bool{
	"ACL":   true,
	"API":   true,
	"ASCII": true,
	"CPU":   true,
	"CSS":   true,
	"DNS":   true,
	"EOF":   true,
	"GUID":  true,
	"HTML":  true,
	"HTTP":  true,
	"HTTPS": true,
	"ID":    true,
	"IP":    true,
	"JSON":  true,
	"LHS":   true,
	"QPS":   true,
	"RAM":   true,
	"RHS":   true,
	"RPC":   true,
	"SLA":   true,
	"SMTP":  true,
	"SQL":   true,
	"SSH":   true,
	"TCP":   true,
	"TLS":   true,
	"TTL":   true,
	"UDP":   true,
	"UI":    true,
	"UID":   true,
	"UUID":  true,
	"URI":   true,
	"URL":   true,
	"UTF8":  true,
	"VM":    true,
	"XML":   true,
	"XMPP":  true,
	"XSRF":  true,
	"XSS":   true,
}

// toCamelCase converts a snake_case or lowercase string to CamelCase with
// Go initialism awareness. Known initialisms (ID, URL, HTTP, etc.) are
// uppercased as a whole word per Go naming conventions.
func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		upper := strings.ToUpper(p)
		if commonInitialisms[upper] {
			result.WriteString(upper)
		} else {
			result.WriteString(strings.ToUpper(p[:1]))
			result.WriteString(p[1:])
		}
	}
	return result.String()
}

// accessorName returns the exported name to use for generated accessor methods
// on the given field. If the field has an explicit AccessorName override (from
// the `accessor` struct tag), it is returned as-is. Otherwise, the field name
// is run through toCamelCase with initialism awareness.
func accessorName(f model.Field) string {
	if f.AccessorName != "" {
		return f.AccessorName
	}
	return toCamelCase(f.Name)
}

// toLowerCamel converts an identifier to lowerCamelCase.
func toLowerCamel(s string) string {
	if len(s) == 0 {
		return s
	}
	// If already CamelCase, just lower the first letter.
	return strings.ToLower(s[:1]) + s[1:]
}

// scalarFields returns fields that are not UID, DType, or edges.
func scalarFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsUID || f.IsDType || f.IsEdge {
			continue
		}
		result = append(result, f)
	}
	return result
}

// nonSliceScalarFields returns scalar fields that are not slices.
// Used in marshal templates to avoid double-emitting slice fields.
func nonSliceScalarFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsUID || f.IsDType || f.IsEdge || strings.HasPrefix(f.GoType, "[]") {
			continue
		}
		result = append(result, f)
	}
	return result
}

// edgeFields returns only edge fields.
func edgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsEdge {
			result = append(result, f)
		}
	}
	return result
}

// privateFields returns all private, non-skipped, non-UID, non-DType fields.
func privateFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && !f.IsSkipped && !f.IsUID && !f.IsDType {
			result = append(result, f)
		}
	}
	return result
}

// privateScalarFields returns private non-edge, non-UID, non-DType fields
// that are not slices (simple scalars like string, int, time.Time).
func privateScalarFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && !f.IsUID && !f.IsDType && !f.IsEdge && !strings.HasPrefix(f.GoType, "[]") {
			result = append(result, f)
		}
	}
	return result
}

// privateSingularEdgeFields returns private edge fields where IsSingularEdge is true.
func privateSingularEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && f.IsEdge && f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// privateMultiEdgeFields returns private edge fields where IsSingularEdge is false.
func privateMultiEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && f.IsEdge && !f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// privateSliceFields returns private non-edge slice fields (e.g., []string, []float64).
func privateSliceFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && !f.IsEdge && strings.HasPrefix(f.GoType, "[]") && !f.IsUID && !f.IsDType {
			result = append(result, f)
		}
	}
	return result
}

// allSingularEdgeFields returns all edge fields (public and private) where IsSingularEdge is true.
func allSingularEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsEdge && f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// allPointerSingularEdgeFields returns edges where GoType is *Entity.
func allPointerSingularEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPointerSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// allValueSingularEdgeFields returns edges where GoType is a bare Entity value.
func allValueSingularEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsValueSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// allSingularViaListFields returns edges where GoType is []*Entity with
// validate:"max=1" or "len=1".
func allSingularViaListFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsSingularViaList {
			result = append(result, f)
		}
	}
	return result
}

// trimPointerPrefix strips leading "*" from a Go type string.
func trimPointerPrefix(s string) string {
	return strings.TrimPrefix(s, "*")
}

// trimSlicePrefix strips leading "[]" from a Go type string.
func trimSlicePrefix(s string) string {
	return strings.TrimPrefix(s, "[]")
}

// trimSliceOfPointerPrefix strips "[]*" prefix and the schema alias dot prefix.
// "[]*schema.Director" → "Director".
func trimSliceOfPointerPrefix(s, alias string) string {
	s = strings.TrimPrefix(s, "[]*")
	s = strings.TrimPrefix(s, alias+".")
	return s
}

// trimSchemaAlias strips the "<alias>." prefix if present.
// "schema.Director" → "Director"; "Director" → "Director".
func trimSchemaAlias(s, alias string) string {
	return strings.TrimPrefix(s, alias+".")
}

// allMultiEdgeFields returns all edge fields (public and private) where IsSingularEdge is false.
func allMultiEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsEdge && !f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// allSliceFields returns all non-edge slice fields (public and private).
func allSliceFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if !f.IsEdge && strings.HasPrefix(f.GoType, "[]") && !f.IsUID && !f.IsDType {
			result = append(result, f)
		}
	}
	return result
}

// marshalFields returns all non-UID, non-DType, non-skipped fields (both public and private).
// This is the union of fields that appear in the marshal alias and mirror structs,
// used to compute which external package imports the marshal file needs.
func marshalFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsSkipped || f.IsUID || f.IsDType {
			continue
		}
		result = append(result, f)
	}
	return result
}

// packageExternalImports returns the union of external imports needed across all
// entities in the package. This is used by the CLI template which lives in a
// separate main package and needs to import external types for conversions.
func packageExternalImports(pkg *model.Package) []ImportSpec {
	var allFields []model.Field
	for _, entity := range pkg.Entities {
		allFields = append(allFields, marshalFields(entity.Fields)...)
	}
	return externalImports(allFields, pkg.Imports)
}

// sanitizePackageName reduces s to a valid lowercase Go package identifier by
// lowercasing and dropping any character that is not a letter or digit (e.g.
// "my-cli" → "mycli"). A leading digit is prefixed with "x" so the result is a
// valid identifier. Used to derive the default CLI library package name.
func sanitizePackageName(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "cli"
	}
	if unicode.IsDigit(rune(out[0])) {
		return "x" + out
	}
	return out
}

// lcFirst lowercases the first character of a string.
func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// elemType strips the leading "[]" from a Go type string, returning the element type.
func elemType(goType string) string {
	return strings.TrimPrefix(goType, "[]")
}

// cliType maps a Go type to the appropriate type for a Kong CLI struct field.
// Kong natively parses string, int, float64, bool, and time.Time flags.
func cliType(goType string) string {
	switch goType {
	case "string", "int", "int64", "float64", "bool":
		return goType
	case "int32":
		return "int"
	case "float32":
		return "float64"
	case "time.Time":
		return "string" // Parsed as string, converted in Run()
	default:
		return "string" // Fallback: accept as string
	}
}

// cliConvert returns a Go expression that converts a CLI field value to the
// entity field's Go type. For types that Kong handles natively (string, int,
// float64, bool), this is an identity — the value is already the correct type.
// For time.Time, this wraps with time.Parse. For external types (e.g.,
// enums.ArchiveStatus, scalars.UUID) that are represented as strings in the
// CLI, this wraps with a type conversion.
//
// Pointer-to-external types (e.g., *dg.VectorFloat32) are not settable via
// CLI string conversion; use cliSettable to gate before calling cliConvert.
func cliConvert(goType, expr string) string {
	switch goType {
	case "string", "int", "int64", "float64", "bool":
		return expr
	case "int32":
		return "int32(" + expr + ")"
	case "float32":
		return "float32(" + expr + ")"
	default:
		// External types (enums, scalars, etc.) are accepted as strings by
		// the CLI and need an explicit type conversion to the target type.
		return goType + "(" + expr + ")"
	}
}

// cliSettable reports whether a field's Go type can be set from a CLI string
// argument. Primitive types (string, int*, float*, bool, time.Time) and
// non-pointer external types (e.g. enums.Status) are settable. Pointer-to-
// external types (e.g. *dg.VectorFloat32) are excluded because there is no
// universal way to parse them from a single string flag.
func cliSettable(goType string) bool {
	switch goType {
	case "string", "int", "int32", "int64", "float32", "float64", "bool", "time.Time":
		return true
	}
	// Pointer types to external packages cannot be auto-converted.
	if strings.HasPrefix(goType, "*") {
		return false
	}
	// Non-pointer types (e.g. enums.Status) can be string-converted.
	return true
}

// hasValidateTags returns true if any field has a non-empty ValidateTag.
func hasValidateTags(fields []model.Field) bool {
	for _, f := range fields {
		if f.ValidateTag != "" {
			return true
		}
	}
	return false
}

// fieldsWithValidation returns fields that have a non-empty ValidateTag.
func fieldsWithValidation(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.ValidateTag != "" {
			result = append(result, f)
		}
	}
	return result
}

// genImports accumulates the imports a merged generated file needs, grouped for
// gofmt-style output: standard library, the modusgraph module, then the schema
// package plus any external (enum/scalar) packages.
type genImports struct {
	std   map[string]bool       // stdlib import paths
	mg    map[string]bool       // modusgraph module import paths
	other map[string]ImportSpec // schema + external imports, keyed by path
}

// newGenImports returns an empty genImports.
func newGenImports() *genImports {
	return &genImports{
		std:   map[string]bool{},
		mg:    map[string]bool{},
		other: map[string]ImportSpec{},
	}
}

// addEntitySideImports adds the imports needed by the entity, accessors, and
// options fragments for e. The conditions mirror the guards the templates
// previously carried inline ($needsIter/$needsSlices/$needsTime/$extImports).
// The accessors scalar-field scan is a superset of the options scan, so options
// contributes nothing additional.
func (g *genImports) addEntitySideImports(e model.Entity, imports map[string]string, schemaPath string) {
	// entity fragment: typed (Option/Apply) + the wrapper base
	// (Wrapper/WrapValue from the wrap package) + schema.
	g.mg["github.com/matthewmcneely/modusgraph/typed"] = true
	g.other["github.com/mlwelles/modusgraph-gen/wrap"] = ImportSpec{Path: "github.com/mlwelles/modusgraph-gen/wrap"}
	g.other[schemaPath] = ImportSpec{Path: schemaPath}

	// accessors fragment.
	multiEdges := allMultiEdgeFields(e.Fields)
	sliceFields := allSliceFields(e.Fields)
	if len(multiEdges) > 0 {
		g.std["iter"] = true
	}
	if len(multiEdges) > 0 || len(sliceFields) > 0 {
		g.std["slices"] = true
	}
	// time + external imports over all non-edge scalar fields (non-slice ∪ slice).
	scalarFields := append(append([]model.Field{}, nonSliceScalarFields(e.Fields)...), sliceFields...)
	for _, f := range scalarFields {
		if strings.Contains(f.GoType, "time.") {
			g.std["time"] = true
		}
	}
	for _, spec := range externalImports(scalarFields, imports) {
		g.other[spec.Path] = spec
	}
}

// addClientSideImports adds the imports needed by the wrapper-client and
// wrapper-query fragments. The wrapper-query fragment also emits By<Field>
// methods for filterable scalar predicates; the typed/filter package is
// added only when the entity has at least one such field.
func (g *genImports) addClientSideImports(schemaPath string, entity model.Entity) {
	g.std["context"] = true
	g.std["iter"] = true
	g.mg["github.com/matthewmcneely/modusgraph"] = true
	g.mg["github.com/matthewmcneely/modusgraph/typed"] = true
	if len(filterableScalarFields(entity.Fields)) > 0 {
		g.mg["github.com/matthewmcneely/modusgraph/typed/filter"] = true
	}
	g.other[schemaPath] = ImportSpec{Path: schemaPath}
}

// block renders the accumulated imports as a gofmt-style import block, with a
// blank line between the stdlib, modusgraph, and schema/external groups. It
// returns "" when no imports were added.
func (g *genImports) block() string {
	if len(g.std)+len(g.mg)+len(g.other) == 0 {
		return ""
	}

	std := make([]string, 0, len(g.std))
	for p := range g.std {
		std = append(std, p)
	}
	sort.Strings(std)

	mg := make([]string, 0, len(g.mg))
	for p := range g.mg {
		mg = append(mg, p)
	}
	sort.Strings(mg)

	others := make([]ImportSpec, 0, len(g.other))
	for _, s := range g.other {
		others = append(others, s)
	}
	sort.Slice(others, func(i, j int) bool { return others[i].Path < others[j].Path })

	var b strings.Builder
	b.WriteString("import (\n")
	wrote := false
	writePlain := func(paths []string) {
		for _, p := range paths {
			b.WriteString("\t\"" + p + "\"\n")
		}
	}
	if len(std) > 0 {
		writePlain(std)
		wrote = true
	}
	if len(mg) > 0 {
		if wrote {
			b.WriteString("\n")
		}
		writePlain(mg)
		wrote = true
	}
	if len(others) > 0 {
		if wrote {
			b.WriteString("\n")
		}
		for _, s := range others {
			if s.Alias != "" {
				b.WriteString("\t" + s.Alias + " \"" + s.Path + "\"\n")
			} else {
				b.WriteString("\t\"" + s.Path + "\"\n")
			}
		}
	}
	b.WriteString(")")
	return b.String()
}

// assembleGenFile builds the body of a merged generated file: a package
// declaration, an optional import block, and the fragment bodies in order. The
// caller passes the result to writeGoFile, which adds the header and gofmt.
func assembleGenFile(pkgName, importBlock string, bodies ...string) string {
	var b strings.Builder
	b.WriteString("package ")
	b.WriteString(pkgName)
	b.WriteString("\n\n")
	if importBlock != "" {
		b.WriteString(importBlock)
		b.WriteString("\n\n")
	}
	for _, body := range bodies {
		trimmed := strings.TrimSpace(body)
		if trimmed == "" {
			continue
		}
		b.WriteString(trimmed)
		b.WriteString("\n\n")
	}
	return b.String()
}

// ImportSpec represents a Go import with an optional alias.
type ImportSpec struct {
	Alias string // Non-empty only when the alias differs from the last path segment.
	Path  string // Full import path.
}

// externalImports returns a sorted list of import specs needed by the given
// fields. It scans field GoTypes for package-qualified types (containing a dot
// that isn't "time."), looks up the full import path in the imports map, and
// returns the unique set. Standard library packages like "time" are excluded
// because templates handle them separately. If a package was imported with an
// alias that differs from the last path segment, the ImportSpec includes the
// alias so templates can emit `alias "path"` syntax.
func externalImports(fields []model.Field, imports map[string]string) []ImportSpec {
	seen := make(map[string]bool)
	var result []ImportSpec
	for _, f := range fields {
		// Strip pointer/slice prefixes to find the package qualifier.
		goType := strings.TrimLeft(f.GoType, "[]*")
		dot := strings.IndexByte(goType, '.')
		if dot < 0 {
			continue
		}
		// Extract the package alias (e.g., "enums" from "enums.ResourceType").
		pkgAlias := goType[:dot]
		// Skip standard library packages that are handled directly in templates.
		if pkgAlias == "time" {
			continue
		}
		path, ok := imports[pkgAlias]
		if !ok || seen[path] {
			continue
		}
		seen[path] = true
		// Include alias only when it differs from the last path segment.
		parts := strings.Split(path, "/")
		alias := ""
		if pkgAlias != parts[len(parts)-1] {
			alias = pkgAlias
		}
		result = append(result, ImportSpec{Alias: alias, Path: path})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Path < result[j].Path })
	return result
}

// searchPredicate returns the dgraph predicate name for the entity's search
// field, or empty string if not searchable.
func searchPredicate(entity model.Entity) string {
	if !entity.Searchable {
		return ""
	}
	for _, f := range entity.Fields {
		if f.Name == entity.SearchField {
			return f.Predicate
		}
	}
	return ""
}

// filterableScalarFields returns the subset of fields that should receive a
// generated By<Field> typed filter method on <Entity>Query. A field is
// filterable when it is a non-edge, non-UID, non-DType scalar with at least
// one index directive and a Go type that maps onto a known filter type
// (see filterTermType).
func filterableScalarFields(fields []model.Field) []model.Field {
	out := make([]model.Field, 0, len(fields))
	for _, f := range fields {
		if f.IsEdge || f.IsUID || f.IsDType || f.IsSkipped || f.IsPrivate {
			continue
		}
		if len(f.Indexes) == 0 {
			continue
		}
		if filterTermType(f) == "" {
			continue
		}
		out = append(out, f)
	}
	return out
}

// filterTermType returns the unqualified Go type name from the filter package
// to use for a field's By<Field>(filters ...filter.X) method signature.
// Returns "" if the field type is not supported by the v1 filter generator.
func filterTermType(f model.Field) string {
	switch f.GoType {
	case "scalars.UUID":
		return "UUID"
	case "string":
		return "String"
	}
	// Any other named string alias could be treated as String, but v1 keeps
	// the rule tight: only literal string and the well-known scalars.UUID.
	// Add cases here as new aliases prove out.
	return ""
}

// filterGroupMethod returns the Builder method name to invoke for a field's
// generated By<Field> method body. Mirrors filterTermType.
func filterGroupMethod(f model.Field) string {
	switch filterTermType(f) {
	case "UUID":
		return "EqGroupUUID"
	case "String":
		return "EqGroupString"
	}
	return ""
}
