// Code generated by modusGraphGen. DO NOT EDIT.

package schema

// SchemaTypeName returns the canonical entity name for Actor.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Actor) SchemaTypeName() string { return "Actor" }

// SchemaPredicates returns the json predicate names declared on Actor,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Actor) SchemaPredicates() []string {
	return []string{
		"name",
		"films",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Actor) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for ContentRating.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*ContentRating) SchemaTypeName() string { return "ContentRating" }

// SchemaPredicates returns the json predicate names declared on ContentRating,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*ContentRating) SchemaPredicates() []string {
	return []string{
		"name",
		"films",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*ContentRating) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Country.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Country) SchemaTypeName() string { return "Country" }

// SchemaPredicates returns the json predicate names declared on Country,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Country) SchemaPredicates() []string {
	return []string{
		"name",
		"films",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Country) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Director.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Director) SchemaTypeName() string { return "Director" }

// SchemaPredicates returns the json predicate names declared on Director,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Director) SchemaPredicates() []string {
	return []string{
		"name",
		"films",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Director) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Film.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Film) SchemaTypeName() string { return "Film" }

// SchemaPredicates returns the json predicate names declared on Film,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Film) SchemaPredicates() []string {
	return []string{
		"name",
		"initialReleaseDate",
		"tagline",
		"genres",
		"countries",
		"ratings",
		"contentRatings",
		"starring",
		"directors",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Film) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Genre.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Genre) SchemaTypeName() string { return "Genre" }

// SchemaPredicates returns the json predicate names declared on Genre,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Genre) SchemaPredicates() []string {
	return []string{
		"name",
		"films",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Genre) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Location.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Location) SchemaTypeName() string { return "Location" }

// SchemaPredicates returns the json predicate names declared on Location,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Location) SchemaPredicates() []string {
	return []string{
		"name",
		"loc",
		"email",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Location) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Performance.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Performance) SchemaTypeName() string { return "Performance" }

// SchemaPredicates returns the json predicate names declared on Performance,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Performance) SchemaPredicates() []string {
	return []string{
		"characterNote",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Performance) SchemaSearchPredicate() string { return "" }

// SchemaTypeName returns the canonical entity name for Rating.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Rating) SchemaTypeName() string { return "Rating" }

// SchemaPredicates returns the json predicate names declared on Rating,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Rating) SchemaPredicates() []string {
	return []string{
		"name",
		"films",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Rating) SchemaSearchPredicate() string { return "name" }

// SchemaTypeName returns the canonical entity name for Studio.
// This is the value modusgraph.Schema requires; it lets modusgraph.Client
// recognize wrapper types via reflection-based Unwrap dispatch.
func (*Studio) SchemaTypeName() string { return "Studio" }

// SchemaPredicates returns the json predicate names declared on Studio,
// excluding the uid and dgraph.type bookkeeping predicates. Order matches
// source-file declaration order.
func (*Studio) SchemaPredicates() []string {
	return []string{
		"name",
		"founder",
		"headquarters",
		"currentHead",
		"ceo",
		"homeBase",
		"parentCompany",
		"films",
		"advisors",
		"tags",
		"scores",
		"weights",
		"flags",
		"milestones",
		"yearFounded",
		"revenue",
		"active",
		"createdAt",
		"embedding",
	}
}

// SchemaSearchPredicate returns the predicate name of the entity's primary
// searchable field (the first field with a fulltext index), or empty string
// if none. Used by tooling that needs a default search target.
func (*Studio) SchemaSearchPredicate() string { return "" }
